services:
  # ── Redis ──────────────────────────────────────────────────────────────────
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  # ── Django app ─────────────────────────────────────────────────────────────
  django:
    build: .
    restart: unless-stopped
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST} # service name — Docker resolves this to the postgres container
      DB_PORT: 5432
      REDIS_CACHE_URL: redis://redis:6379/1
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      SENTRY_DSN: ${SENTRY_DSN}
      FERNET_KEY: ${FERNET_KEY}
      DJANGO_ENV: ${DJANGO_ENV}
      DEFAULT_FROM_EMAIL: ${DEFAULT_FROM_EMAIL}
      R2_ACCESS_KEY_ID: ${R2_ACCESS_KEY_ID}
      R2_SECRET_ACCESS_KEY: ${R2_SECRET_ACCESS_KEY}
      R2_BUCKET_NAME: ${R2_BUCKET_NAME}
      R2_ENDPOINT_URL: ${R2_ENDPOINT_URL}
      DOMAIN: ${DOMAIN}
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - static_files:/app/staticfiles
    expose:
      - "8000"

  # ── Celery worker ──────────────────────────────────────────────────────────
  celery:
    build: .
    command: worker
    restart: unless-stopped
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST} # service name — Docker resolves this to the postgres container
      DB_PORT: 5432
      REDIS_CACHE_URL: redis://redis:6379/1
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
      FERNET_KEY: ${FERNET_KEY}
      SENTRY_DSN: ${SENTRY_DSN}
      DJANGO_ENV: ${ENVIRONMENT}
      DEFAULT_FROM_EMAIL: ${DEFAULT_FROM_EMAIL}
      R2_ACCESS_KEY_ID: ${R2_ACCESS_KEY_ID}
      R2_SECRET_ACCESS_KEY: ${R2_SECRET_ACCESS_KEY}
      R2_BUCKET_NAME: ${R2_BUCKET_NAME}
      R2_ENDPOINT_URL: ${R2_ENDPOINT_URL}
      DOMAIN: ${DOMAIN}
    depends_on:
      redis:
        condition: service_healthy

  # ── Nginx ──────────────────────────────────────────────────────────────────
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_files:/app/staticfiles:ro
    depends_on:
      - django

volumes:
  redis_data:
  static_files:
